<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jewel Johnson">
<meta name="dcterms.date" content="2022-09-19">
<meta name="description" content="Level up your regression knowledge using multiple explanatory variables">

<title>SciQuest - Intermediate Regression in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/social-share-0.1.0/social-share.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/social-share-0.1.0/all.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EVCS615JQR"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-EVCS615JQR', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<script type="module" src="../../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="../../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">

<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css">
<meta property="og:title" content="SciQuest - Intermediate Regression in R">
<meta property="og:description" content="Level up your regression knowledge using multiple explanatory variables">
<meta property="og:image" content="https://sciquest.netlify.app/tutorials/stat_basic/images/inter_reg.png">
<meta property="og:site-name" content="SciQuest">
<meta property="og:image:height" content="1080">
<meta property="og:image:width" content="1920">
<meta name="twitter:title" content="SciQuest - Intermediate Regression in R">
<meta name="twitter:description" content="Level up your regression knowledge using multiple explanatory variables">
<meta name="twitter:image" content="https://sciquest.netlify.app/tutorials/stat_basic/images/inter_reg.png">
<meta name="twitter:image-height" content="1080">
<meta name="twitter:image-width" content="1920">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">SciQuest</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html" rel="" target="">
 <span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://jeweljohnsonj.github.io/jewel_resume/" rel="" target="">
 <span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jeweljohnsonj/SciQuest" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/jeweljohnsonj" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Intermediate Regression in R</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          Level up your regression knowledge using multiple explanatory variables
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">regression</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://sciquest.netlify.app/">Jewel Johnson</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 19, 2022</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">April 15, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#linear-regression-using-multiple-variables" id="toc-linear-regression-using-multiple-variables" class="nav-link" data-scroll-target="#linear-regression-using-multiple-variables"><span class="header-section-number">2</span> Linear regression using multiple variables</a></li>
  <li><a href="#understanding-the-summary-of-a-multivariate-linear-model" id="toc-understanding-the-summary-of-a-multivariate-linear-model" class="nav-link" data-scroll-target="#understanding-the-summary-of-a-multivariate-linear-model"><span class="header-section-number">3</span> Understanding the summary of a multivariate linear model</a></li>
  <li><a href="#making-predictions-using-a-multivariate-linear-model" id="toc-making-predictions-using-a-multivariate-linear-model" class="nav-link" data-scroll-target="#making-predictions-using-a-multivariate-linear-model"><span class="header-section-number">4</span> Making predictions using a multivariate linear model</a></li>
  <li><a href="#assessing-a-multivariate-linear-model-fit" id="toc-assessing-a-multivariate-linear-model-fit" class="nav-link" data-scroll-target="#assessing-a-multivariate-linear-model-fit"><span class="header-section-number">5</span> Assessing a multivariate linear model fit</a>
  <ul class="collapse">
  <li><a href="#adjusted-r-square-value" id="toc-adjusted-r-square-value" class="nav-link" data-scroll-target="#adjusted-r-square-value"><span class="header-section-number">5.1</span> Adjusted R square value</a></li>
  </ul></li>
  <li><a href="#linear-regression-with-interacting-terms" id="toc-linear-regression-with-interacting-terms" class="nav-link" data-scroll-target="#linear-regression-with-interacting-terms"><span class="header-section-number">6</span> Linear regression with interacting terms</a></li>
  <li><a href="#plotting-linear-model-with-an-interaction-term" id="toc-plotting-linear-model-with-an-interaction-term" class="nav-link" data-scroll-target="#plotting-linear-model-with-an-interaction-term"><span class="header-section-number">7</span> Plotting linear model with an interaction term</a></li>
  <li><a href="#simpsons-paradox" id="toc-simpsons-paradox" class="nav-link" data-scroll-target="#simpsons-paradox"><span class="header-section-number">8</span> Simpson’s Paradox</a></li>
  <li><a href="#visualizing-linear-models-with-two-numerical-explanatory-variables" id="toc-visualizing-linear-models-with-two-numerical-explanatory-variables" class="nav-link" data-scroll-target="#visualizing-linear-models-with-two-numerical-explanatory-variables"><span class="header-section-number">9</span> Visualizing linear models with two numerical explanatory variables</a></li>
  <li><a href="#visualizing-logistic-models-with-two-numerical-explanatory-variables" id="toc-visualizing-logistic-models-with-two-numerical-explanatory-variables" class="nav-link" data-scroll-target="#visualizing-logistic-models-with-two-numerical-explanatory-variables"><span class="header-section-number">10</span> Visualizing logistic models with two numerical explanatory variables</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">11</span> Conclusion</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/jeweljohnsonj/SciQuest/edit/main/tutorials/stat_basic/inter_reg.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/jeweljohnsonj/SciQuest/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell">
<div class="sourceCode cell-code hidden" id="cb1" data-startfrom="28" data-source-offset="0"><pre class="sourceCode js code-with-copy"><code class="sourceCode javascript" style="counter-reset: source-line 27;"><span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="pp">require</span>(<span class="st">"https://cdn.jsdelivr.net/npm/juxtaposejs@1.1.6/build/js/juxtapose.min.js"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="op">.</span><span class="fu">catch</span>(() <span class="kw">=&gt;</span> <span class="kw">null</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display hidden">
<div id="ojs-cell-1" data-nodetype="expression">

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this article you will learn;</p>
<ol type="1">
<li><p>How to build models with two or more explanatory variables</p></li>
<li><p>How to interpret multivariate models</p></li>
<li><p>How to predict values using a multivariate model</p></li>
<li><p>Assessing a multivariate model</p></li>
<li><p>Building models with interaction terms and plotting them</p></li>
<li><p>What is Simpson’s paradox</p></li>
<li><p>Visualising models with two numerical explanatory variables</p></li>
</ol>
</div>
</div>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>This tutorial is a sequel to the previous tutorial which covered the basics of regression. Here we will extend our knowledge to build models using more than one explanatory variable, how to visualise them and how to interpret the model summaries.</p>
</section>
<section id="linear-regression-using-multiple-variables" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="linear-regression-using-multiple-variables"><span class="header-section-number">2</span> Linear regression using multiple variables</h2>
<p>In the previous tutorial, we have seen how to build a linear model with a single exploratory variable. Now we will see how to build linear models using two variables.</p>
<p>We will use the <code>HorsePrices</code> dataset from the <code>{Stat2Data}</code> package in R. The dataset contains the price and related characteristics of horses listed for sale on the internet. Using the dataset, we will see how the price of a horse (<code>Price</code>) changes according to its age (<code>Age</code>) and also dues to its sex (<code>Sex</code>) using a linear model. Here, we have a numerical and a categorical variable as the explanatory variables. First, let us plot the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(Stat2Data)) <span class="fu">install.packages</span>(<span class="st">'Stat2Data'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in the price of the horse as a function of age and sex?"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (dollars)"</span>) <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>At a glance, for intermediately aged horses, the price is high compared to the rest of the age range. Also, female horses seem to have to be priced less compared to males. Let us see if that is the case by building a linear model. To predict the response variable using multiple explanatory variables, we will append them using the <code>+</code> sign.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model output</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Age + Sex, data = HorsePrices)

Residuals:
   Min     1Q Median     3Q    Max 
-24988 -10296  -1494   8286  27653 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  18199.7     4129.3   4.407 6.03e-05 ***
Age           -220.1      393.8  -0.559    0.579    
Sexm         17008.6     3639.6   4.673 2.52e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12540 on 47 degrees of freedom
Multiple R-squared:  0.3283,    Adjusted R-squared:  0.2997 
F-statistic: 11.48 on 2 and 47 DF,  p-value: 8.695e-05</code></pre>
</div>
</div>
<p>Unlike the earlier case with one explanatory variable, we now have two coefficient values and an intercept value. We will soon see how to interpret the coefficient values. But for now, we can see that their age does not significantly explain the variance seen in price but sex does.</p>
<p>Now let us try plotting the model. Instead of using the <code>geom_smooth()</code> function in the <code>{ggplot2}</code> package in R, we will use the <code>geom_parallel_slopes()</code> function from the <code>{moderndive}</code> package in R. We will later see why we did not use the <code>geom_smooth()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(moderndive)) <span class="fu">install.packages</span>(<span class="st">'moderndive'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in the price of the horse as a function of age and sex?"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (dollars)"</span>) <span class="sc">+</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_parallel_slopes</span>() <span class="sc">+</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is a difference in price between male and female horses but their prices are not changing across age. This is exactly what we saw in the model summary results. You can also see that the lines are parallel to each other.</p>
</section>
<section id="understanding-the-summary-of-a-multivariate-linear-model" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="understanding-the-summary-of-a-multivariate-linear-model"><span class="header-section-number">3</span> Understanding the summary of a multivariate linear model</h2>
<p>Given below is the summary output of the multivariate model we built earlier.</p>
<p><img src="images/lm_summary_multi.png" class="img-fluid"></p>
<ol type="1">
<li><p>In section 1, we have the model formula we used for building the model.</p></li>
<li><p>In section 2, we have the first quartile, median and third quartile of the residuals of the model. This tells us whether the residuals are normally distributed if the median value is close to zero and, the first and third quartile values are approximately the same in magnitude.</p></li>
<li><p>In section 3, we have the coefficient values of the exploratory variables. Please remember that the variable ‘sex’ has two levels; female and male. By default, R calculates the intercept value for the first level in the first categorical response variable in the model formula. Here, in our case, that first level is female. Therefore, the intercept value gives us the average price value for female horses when age is 0. So here, the y-intercept value of 18199 corresponds to the average price of female horses when age is 0. The second value is the slope of Age, which is -220.1, which corresponds to a decrease in the price by a value of 220.1 dollars when the age of the horse increases by 1 year. The third value corresponds to the difference in the y-intercept value for males as compared to the main intercept value, which is for females and is 18199. In short, it tells us that male horses with age 0 are priced 17008 dollars more on average when compared to female horses. If we want to see the individual averages of the levels in the categorical exploratory variables, then we should use <code>-1</code> in the model formula, which is something we saw in the earlier tutorial.</p></li>
<li><p>Section 4 contains metrics which assess model performance. In the earlier tutorial, we saw what residual standard error and R squared values means. Adjusted R square value is a metric similar to R squared value but is calculated for models with multiple explanatory variables. Like R squared, it tells us how much variance seen in the response variable is explained by the explanatory variables and the value lies between 0 and 1. Here we have around 30% variance seen in price explained by both age and sex of the horses.</p></li>
</ol>
</section>
<section id="making-predictions-using-a-multivariate-linear-model" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="making-predictions-using-a-multivariate-linear-model"><span class="header-section-number">4</span> Making predictions using a multivariate linear model</h2>
<p>As seen earlier, we can use the models to predict values outside the dataset. We will use the <code>expand_grid()</code> function to make a data frame containing the values for which we want the model to predict.</p>
<p>Let us predict the price of a 20-year-old male horse.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Making a exploratory data frame</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">Sex =</span> <span class="st">"m"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Age =</span> <span class="dv">20</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting values</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_lm, explorartory_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
30806.54 </code></pre>
</div>
</div>
<p>The model predicts that the price of such a horse would be 30806 dollars.</p>
</section>
<section id="assessing-a-multivariate-linear-model-fit" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="assessing-a-multivariate-linear-model-fit"><span class="header-section-number">5</span> Assessing a multivariate linear model fit</h2>
<section id="adjusted-r-square-value" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="adjusted-r-square-value"><span class="header-section-number">5.1</span> Adjusted R square value</h3>
<p>For a simple linear model, we have seen how to interpret the R-squared value, Residual standard error (RSE) value and the Root mean square error (RMSE) value. For a multivariate linear model, the R squared value will be greater compared to a simple linear model and this is because as you add more variables to explain the response variable, the model tends to best fit the available dataset. And in doing so, the model will no longer be useful to make inferences about the general population. So the adjusted R-square value is a metric that describes the percentage of variance explained by the explanatory variable but is measured by penalising the model with multiple explanatory variables by assigning a small penalty term for each additional explanatory variable. The formula for calculating the adjusted R square value is as follows;</p>
<p><span class="math display">\bar{R^2} = 1-(1-R^2)\frac{n_{obs}-1}{n_{obs}-n_{var}-1} </span></p>
<ul>
<li><span class="math inline">\bar{R^2}</span> = Adjusted R squared value</li>
<li><span class="math inline">R^2</span> = R squared value</li>
<li><span class="math inline">n_{obs}</span> = Number of observations</li>
<li><span class="math inline">n_{var}</span> = Number of variables in the model</li>
</ul>
<p>Please note that the adjusted R square value is always lower than the R squared value.</p>
<p>In R, we can extract the adjusted R square value of a model using the <code>glance()</code> and <code>pull()</code> functions in the <code>{broom}</code> and <code>{dplyr}</code> packages in R. The adjusted R square in the table would be under the <code>adj.r.squared</code> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting adjusted R square value</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>model_lm <span class="sc">%&gt;%</span> <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(adj.r.squared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2996728</code></pre>
</div>
</div>
</section>
</section>
<section id="linear-regression-with-interacting-terms" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="linear-regression-with-interacting-terms"><span class="header-section-number">6</span> Linear regression with interacting terms</h2>
<p>So far we have built linear models using the <code>HorsePrices</code> dataset where we looked at the association between age and sex on the price of the horses. Now consider another variable, which is the height of the horses (<code>Height</code>). First, let us visualize the heights of the horses of their respective sex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sex, Height, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Height of horses with respect to their sex"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sex"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Height (in hands)"</span>) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the graph, it seems like male horses are typically taller when compared to female horses according to the dataset at hand. Now if we are building a linear model, where we are interested to see the association of height and sex of horses on the price of the horses, we will have to take into consideration that female and male horses have different height distribution, as seen with the box plot above.</p>
<p>One way to account for this is to build separate models using a filtered dataset for each the sex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering horses by their sex</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>male_horses <span class="ot">&lt;-</span> HorsePrices <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"m"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>female_horses <span class="ot">&lt;-</span> HorsePrices <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"f"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear models</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>male_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height, <span class="at">data =</span> male_horses)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>female_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height, <span class="at">data =</span> female_horses)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(male_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Height, data = male_horses)

Residuals:
     Min       1Q   Median       3Q      Max 
-18671.5  -6325.5     29.9   9001.5  24001.5 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  -120546      66679  -1.808   0.0818 .
Height          9346       4016   2.327   0.0277 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11830 on 27 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1671,    Adjusted R-squared:  0.1362 
F-statistic: 5.416 on 1 and 27 DF,  p-value: 0.0277</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(female_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Height, data = female_horses)

Residuals:
   Min     1Q Median     3Q    Max 
-15366  -6145  -2716   6127  27277 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    57330      74949   0.765    0.455
Height         -2515       4710  -0.534    0.601

Residual standard error: 11550 on 16 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.01751,   Adjusted R-squared:  -0.0439 
F-statistic: 0.2851 on 1 and 16 DF,  p-value: 0.6007</code></pre>
</div>
</div>
<p>The coefficient values for the two models are very different. For male horses, a unit change in height contributes to a 9346 dollar increase in the price of the horse, but for female horses, the opposite occurs, a unit change in height decreases the price by 2515 dollars (though this difference is not significantly different). Thus we can say that the height of a horse depends on its sex. In other words, the variable height and the variable sex interact with each other. Instead of making separate models like this, R has an easy way to show interacting terms. Instead of using the <code>+</code>, we can use the <code>*</code> sign to indicate an interaction between two variables. The <code>:</code> sign can also be used to explicitly mention which terms interact. The codes given below show how to account for interaction between height and sex for the given dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model with interaction</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>lm_model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height <span class="sc">*</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Same model as above but explicitly mentioning interaction terms</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>lm_model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height <span class="sc">+</span> Sex <span class="sc">+</span> Height<span class="sc">:</span>Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Height * Sex, data = HorsePrices)

Residuals:
     Min       1Q   Median       3Q      Max 
-18671.5  -6410.3   -671.5   6971.0  27276.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    57330      76078   0.754   0.4552  
Height         -2515       4781  -0.526   0.6016  
Sexm         -177876     100786  -1.765   0.0847 .
Height:Sexm    11861       6222   1.906   0.0633 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11730 on 43 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.4086,    Adjusted R-squared:  0.3673 
F-statistic: 9.901 on 3 and 43 DF,  p-value: 4.377e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Height + Sex + Height:Sex, data = HorsePrices)

Residuals:
     Min       1Q   Median       3Q      Max 
-18671.5  -6410.3   -671.5   6971.0  27276.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    57330      76078   0.754   0.4552  
Height         -2515       4781  -0.526   0.6016  
Sexm         -177876     100786  -1.765   0.0847 .
Height:Sexm    11861       6222   1.906   0.0633 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11730 on 43 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.4086,    Adjusted R-squared:  0.3673 
F-statistic: 9.901 on 3 and 43 DF,  p-value: 4.377e-05</code></pre>
</div>
</div>
<p>Since the female is the first level in the variable <code>Sex</code>, the intercept is estimated for female horses. This is the same value that we got from the <code>female_lm</code> model we made earlier. We also got the slope value for height, which is calculated for female horses (the same value as that from the <code>female_lm</code> model). The value for male horses is given as <code>Sexm</code> as is -177876, this value is relative to female horses and is given as the difference between the y-intercepts. We can find the actual y-intercept value for males by adding the <code>Sexm</code> value and the <code>(Intercept)</code> value which is -120546 ( = 57330 + -177876). This is the intercept value for male horses which we got from the <code>male_lm</code> model earlier. Now let us look at the <code>Height:Sexm</code> value, which is given as 11861. This is the slope value showing how the price change when height change for male horses, but it is calculated relative to female horses. To get the actual slope for male horses, we have to add the slope of <code>Height</code> and <code>Height:Sexm</code> values. In doing so we get a value of 9346 ( = -2515 + 11861) which is the slope of <code>Height</code>, which we got from the <code>male_lm</code> model earlier.</p>
</section>
<section id="plotting-linear-model-with-an-interaction-term" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="plotting-linear-model-with-an-interaction-term"><span class="header-section-number">7</span> Plotting linear model with an interaction term</h2>
<p>When we were using the <code>geom_parallel_slopes()</code> function from the <code>{moderndive}</code> package, I mentioned that we will not use <code>geom_smooth()</code> function from the <code>{ggplot2}</code> package. This is because when we specify the <code>col</code> variable, the <code>geom_smooth()</code> function automatically plots the trend line by considering the x-axis variable and the colour variable to be interacting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting linear model with interaction terms</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Height, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Price of horses with respect to their height and sex"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Height (in hands)"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (in dollars)"</span>) <span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The slope for male horses is steeper than for female horses. This indicates that male horses have their price increased significantly as their height increased. Whereas female horses have their price change non significantly when their height change. This is exactly what we see in the <code>male_lm</code> and <code>female_lm</code> model coefficients.</p>
</section>
<section id="simpsons-paradox" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="simpsons-paradox"><span class="header-section-number">8</span> Simpson’s Paradox</h2>
<p>Simpson’s paradox occurs when a result conveyed using the whole dataset is different from the results conveyed using the different groups within the same dataset. In simple words, the results of the model change drastically due to the inclusion of a variable which was previously not included in the model. Let’s see what this means.</p>
<p>We will use the <code>penguins</code> dataset from the <code>{palmerpenguins}</code> package in R. The dataset contains body measurements taken from three different species of penguins from Antarctica. Let us build a model where the body mass (<code>body_mass_g</code>) is predicted by bill depth (<code>bill_depth_mm</code>) alone. Let us also build another build with the same model formula as before but this time, we will include an interaction term between bill depth and species (<code>species</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(palmerpenguins)) <span class="fu">install.packages</span>(<span class="st">'palmerpenguins'</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g  <span class="sc">~</span> bill_depth_mm, <span class="at">data =</span> penguins)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model with interaction term</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>model_lm_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g  <span class="sc">~</span> bill_depth_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ bill_depth_mm, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-1607.38  -510.10   -66.96   462.43  1819.28 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    7488.65     335.22   22.34   &lt;2e-16 ***
bill_depth_mm  -191.64      19.42   -9.87   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 708.1 on 340 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.2227,    Adjusted R-squared:  0.2204 
F-statistic: 97.41 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ bill_depth_mm * species, data = penguins)

Residuals:
    Min      1Q  Median      3Q     Max 
-845.89 -254.74  -28.46  228.01 1161.41 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     -283.28     437.94  -0.647   0.5182    
bill_depth_mm                    217.15      23.82   9.117   &lt;2e-16 ***
speciesChinstrap                 247.06     829.77   0.298   0.7661    
speciesGentoo                   -175.71     658.43  -0.267   0.7897    
bill_depth_mm:speciesChinstrap   -12.53      45.01  -0.278   0.7809    
bill_depth_mm:speciesGentoo      152.29      40.49   3.761   0.0002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 354.9 on 336 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.807, Adjusted R-squared:  0.8041 
F-statistic:   281 on 5 and 336 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We get a rather interesting and contradicting set of results when we compare the summary outputs for both models. In the model without the species variable, greater bill depth predicts lower body mass in penguins. But, when we add the species variable, the trend reverses, increasing bill depth is associated with an increase in body mass.</p>
<p>It is easier to plot the models and see. Use the slider to see the difference between the plots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model wihtout interaction term</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g)) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm + species"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model with interaction term</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> species)) <span class="sc">+</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="juxtapose" data-startingposition="50%">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model wihtout interaction term</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm + species"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model with interaction term</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> species)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>So it is always better to visualize the dataset and build models according to the question at hand.</p>
</section>
<section id="visualizing-linear-models-with-two-numerical-explanatory-variables" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="visualizing-linear-models-with-two-numerical-explanatory-variables"><span class="header-section-number">9</span> Visualizing linear models with two numerical explanatory variables</h2>
<p>Often you will be building models with two or more two explanatory variables. If some of those explanatory variables are categorical then it is easier to plot them as we can assign different colour or shape variables and we can also use faceting. But if they are all numerical variables then it is kind of difficult to plot them. We can either rely on three-dimensional plots or use a continuous colour scale gradient in a two-dimensional plot. Let us see how to plot the graphs.</p>
<p>We will again use the <code>penguins</code> dataset from the <code>{palmerpenguins}</code> package in R. We will build a model to predict body mass (<code>body_mass_g</code>) using bill length (<code>bill_length_mm</code>) and bill depth (<code>bill_depth_mm</code>). Let us first try to plot a 3D plot using the <code>scatter3D()</code> function from the <code>{plot3D}</code> package in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(plot3D)) <span class="fu">install.packages</span>(<span class="st">'plot3D'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plot3D)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting a 3D plot</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter3D</span>(penguins<span class="sc">$</span>body_mass_g, penguins<span class="sc">$</span>bill_depth_mm, penguins<span class="sc">$</span>bill_length_mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Well, 3D plotting is a mess, as you can see from the above plot. It is very hard to make out any useful findings using the graph above. So instead of this, we can return to our conventional 2D plot where we can use a continuous colour gradient to visualize the third numerical variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth and bill length in three different species of penguins"</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the graph, it roughly seems like penguins with greater body mass have a longer and narrower bill. We can further subdivide this plot by the species category using faceting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Making a function to make line breaks in text</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>addline_format <span class="ot">&lt;-</span> <span class="cf">function</span>(x,...){</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gsub</span>(<span class="st">','</span>,<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>,x)}</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">addline_format</span>(<span class="st">"Body mass predcited by bill depth and bill length,in three different species of penguins"</span>),</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> species) <span class="sc">+</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When we group the data according to different species, we get the opposite result as compared before. Here, we can see that penguins with heavier body mass have broader and longer bills.</p>
<p>Now let us plot the predicted values from the linear models to see the general trend of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Making prediction</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> bill_depth_mm <span class="sc">*</span> bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">bill_depth_mm =</span> <span class="fu">seq</span>(<span class="dv">15</span>,<span class="dv">25</span>,<span class="dv">1</span>),</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">bill_length_mm =</span> <span class="fu">seq</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">1</span>),</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="ot">&lt;-</span> explorartory_values <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">body_mass_g =</span> <span class="fu">predict</span>(model_lm, explorartory_values)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph with predicted values</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth and bill length </span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="st">in three different species of penguins"</span>,</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> species) <span class="sc">+</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> predicted_values, <span class="fu">aes</span>(<span class="at">y =</span> body_mass_g), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We got a nice gradient-coloured graph. From the predicted values we got from the model we can understand how body mass changes with bill depth and bill length. We can see two clear patterns. For penguins with lower bill length values, the body mass increases as bill depth increases. The opposite is true for penguins with larger values for bill length. For these penguins, body mass decreases as bill depth increases.</p>
</section>
<section id="visualizing-logistic-models-with-two-numerical-explanatory-variables" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="visualizing-logistic-models-with-two-numerical-explanatory-variables"><span class="header-section-number">10</span> Visualizing logistic models with two numerical explanatory variables</h2>
<p>We have seen how to include two or more variables in a linear model. The same procedure applies to logistic models. Now we will see how to visualize a logistic model with two or more numerical variables.</p>
<p>We will use the <code>CreditCard</code> dataset in the <code>{AER}</code> package in R. The dataset contains the credit history of a sample of applicants for a type of credit card. We will predict to see the success of the acceptance of the credit card application (<code>card</code>) using the yearly income (<code>income</code>) and age (<code>age</code>) of the applicant. The code for making the plot is very similar to that we have seen earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(AER)) <span class="fu">install.packages</span>(<span class="st">'AER'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"CreditCard"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Making prediction</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>model_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(card <span class="sc">~</span> income <span class="sc">*</span> age, <span class="at">data =</span> CreditCard, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">income =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">20</span>,<span class="dv">1</span>),</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">90</span>,<span class="dv">1</span>),</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="ot">&lt;-</span> explorartory_values <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">card =</span> <span class="fu">predict</span>(model_logistic, explorartory_values, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph with predicted values</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CreditCard, <span class="fu">aes</span>(income, <span class="fu">as.integer</span>(card)<span class="sc">-</span><span class="dv">1</span>, <span class="at">col =</span> age)) <span class="sc">+</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Does income and age affect the success in accepting a credit card application?"</span>,</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Yearly income (in USD 10,000)"</span>,</span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability of success in accepting a credit card application"</span>) <span class="sc">+</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient2</span>() <span class="sc">+</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> predicted_values, <span class="fu">aes</span>(<span class="at">y =</span> card), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="inter_reg_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We get some interesting results. People with higher yearly incomes have a higher chance of getting a credit card. But for age, younger people with lower yearly income have more chance of getting a credit card as compared to older people with the same level of yearly income. But this trend reverses when yearly income crosses 50,000 dollars.</p>
</section>
<section id="conclusion" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">11</span> Conclusion</h2>
<p>It is time to wrap up! In this tutorial we have learned the following things;</p>
<ol type="1">
<li><p>How to build models with two or more explanatory variables</p></li>
<li><p>How to interpret multivariate models</p></li>
<li><p>How to predict values using a multivariate model</p></li>
<li><p>Assessing a multivariate model</p></li>
<li><p>Building models with interaction terms and plotting them</p></li>
<li><p>What is Simpson’s paradox</p></li>
<li><p>Visualising models with two numerical explanatory variables</p></li>
</ol>
<!-- Do not forget to put flag counter -->
<p><a hidden="" href="https://info.flagcounter.com/ynrK"><img src="https://s11.flagcounter.com/count2/ynrK/bg_000000/txt_FFFFFF/border_F0F0F0/columns_5/maxflags_25/viewers_0/labels_1/pageviews_1/flags_0/percent_0/" alt="Flag Counter" border="0"></a></p>


<!-- -->

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div id="quarto-reuse" class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">https://creativecommons.org/licenses/by/4.0/</a></div></div></section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{johnson2022,
  author = {Johnson, Jewel},
  title = {Intermediate {Regression} in {R}},
  date = {2022-09-19},
  url = {https://sciquest.netlify.app//tutorials/stat_basic/inter_reg.html},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-johnson2022" class="csl-entry quarto-appendix-citeas" role="listitem">
Johnson, Jewel. 2022. <span>“Intermediate Regression in R.”</span>
September 19, 2022. <a href="https://sciquest.netlify.app//tutorials/stat_basic/inter_reg.html">https://sciquest.netlify.app//tutorials/stat_basic/inter_reg.html</a>.
</div></div></section></div></main> <!-- /main -->
<script type="ojs-module-contents">
{"contents":[{"methodName":"interpret","cellName":"ojs-cell-1","inline":false,"source":"require(\"https://cdn.jsdelivr.net/npm/juxtaposejs@1.1.6/build/js/juxtapose.min.js\")\n  .catch(() => null)\n"}]}
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../../tutorials/stat_basic";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "../..";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="jeweljohnsonj/SciQuest" data-repo-id="R_kgDOHW124A" data-category="General" data-category-id="DIC_kwDOHW124M4CPNVL" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb32" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Intermediate Regression in R"</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Level up your regression knowledge using multiple explanatory variables"</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "09/19/2022"</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> last-modified</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">    css:</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">      - https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> images/inter_reg.png</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [regression]</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="an">filters:</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co">   - social-share</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="an">share:</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co">  permalink: "https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html"</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co">  description: "Intermediate Regression in R"</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="co">  twitter: true</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="co">  facebook: true</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="co">  reddit: true</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co">  stumble: true</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co">  tumblr: true</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co">  linkedin: true</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co">  email: true</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="in">```{ojs}</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="co">//| output: false</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="co">//| echo: false</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a><span class="pp">require</span>(<span class="st">"https://cdn.jsdelivr.net/npm/juxtaposejs@1.1.6/build/js/juxtapose.min.js"</span>)</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>  <span class="op">.</span><span class="fu">catch</span>(() <span class="kw">=&gt;</span> <span class="kw">null</span>)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>:::{.callout-note}</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## TL;DR</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>In this article you will learn;</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a><span class="ss">1.    </span>How to build models with two or more explanatory variables</span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a><span class="ss">2.    </span>How to interpret multivariate models</span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a><span class="ss">3.    </span>How to predict values using a multivariate model</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a><span class="ss">4.    </span>Assessing a multivariate model</span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a><span class="ss">5.    </span>Building models with interaction terms and plotting them</span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a><span class="ss">6.    </span>What is Simpson's paradox</span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a><span class="ss">7.    </span>Visualising models with two numerical explanatory variables</span>
<span id="cb32-53"><a href="#cb32-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-54"><a href="#cb32-54" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-56"><a href="#cb32-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb32-57"><a href="#cb32-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-58"><a href="#cb32-58" aria-hidden="true" tabindex="-1"></a>This tutorial is a sequel to the previous tutorial which covered the basics of regression. Here we will extend our knowledge to build models using more than one explanatory variable, how to visualise them and how to interpret the model summaries.</span>
<span id="cb32-59"><a href="#cb32-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-60"><a href="#cb32-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linear regression using multiple variables</span></span>
<span id="cb32-61"><a href="#cb32-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-62"><a href="#cb32-62" aria-hidden="true" tabindex="-1"></a>In the previous tutorial, we have seen how to build a linear model with a single exploratory variable. Now we will see how to build linear models using two variables. </span>
<span id="cb32-63"><a href="#cb32-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-64"><a href="#cb32-64" aria-hidden="true" tabindex="-1"></a>We will use the <span class="in">`HorsePrices`</span> dataset from the <span class="in">`{Stat2Data}`</span> package in R. The dataset contains the price and related characteristics of horses listed for sale on the internet. Using the dataset, we will see how the price of a horse (<span class="in">`Price`</span>) changes according to its age (<span class="in">`Age`</span>) and also dues to its sex (<span class="in">`Sex`</span>) using a linear model. Here, we have a numerical and a categorical variable as the explanatory variables. First, let us plot the data.</span>
<span id="cb32-65"><a href="#cb32-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-68"><a href="#cb32-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-69"><a href="#cb32-69" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(Stat2Data)) <span class="fu">install.packages</span>(<span class="st">'Stat2Data'</span>)</span>
<span id="cb32-70"><a href="#cb32-70" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-71"><a href="#cb32-71" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-72"><a href="#cb32-72" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-73"><a href="#cb32-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-74"><a href="#cb32-74" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-75"><a href="#cb32-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-76"><a href="#cb32-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb32-77"><a href="#cb32-77" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-78"><a href="#cb32-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in the price of the horse as a function of age and sex?"</span>,</span>
<span id="cb32-79"><a href="#cb32-79" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb32-80"><a href="#cb32-80" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (dollars)"</span>) <span class="sc">+</span></span>
<span id="cb32-81"><a href="#cb32-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-82"><a href="#cb32-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-83"><a href="#cb32-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-84"><a href="#cb32-84" aria-hidden="true" tabindex="-1"></a>At a glance, for intermediately aged horses, the price is high compared to the rest of the age range. Also, female horses seem to have to be priced less compared to males. Let us see if that is the case by building a linear model. To predict the response variable using multiple explanatory variables, we will append them using the <span class="in">`+`</span> sign.</span>
<span id="cb32-85"><a href="#cb32-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-88"><a href="#cb32-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-89"><a href="#cb32-89" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-90"><a href="#cb32-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-91"><a href="#cb32-91" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-92"><a href="#cb32-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-93"><a href="#cb32-93" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb32-94"><a href="#cb32-94" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb32-95"><a href="#cb32-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-96"><a href="#cb32-96" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model output</span></span>
<span id="cb32-97"><a href="#cb32-97" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm)</span>
<span id="cb32-98"><a href="#cb32-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-99"><a href="#cb32-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-100"><a href="#cb32-100" aria-hidden="true" tabindex="-1"></a>Unlike the earlier case with one explanatory variable, we now have two coefficient values and an intercept value. We will soon see how to interpret the coefficient values. But for now, we can see that their age does not significantly explain the variance seen in price but sex does.</span>
<span id="cb32-101"><a href="#cb32-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-102"><a href="#cb32-102" aria-hidden="true" tabindex="-1"></a>Now let us try plotting the model. Instead of using the <span class="in">`geom_smooth()`</span> function in the <span class="in">`{ggplot2}`</span> package in R, we will use the <span class="in">`geom_parallel_slopes()`</span> function from the <span class="in">`{moderndive}`</span> package in R. We will later see why we did not use the <span class="in">`geom_smooth()`</span> function.</span>
<span id="cb32-103"><a href="#cb32-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-106"><a href="#cb32-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-107"><a href="#cb32-107" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(moderndive)) <span class="fu">install.packages</span>(<span class="st">'moderndive'</span>)</span>
<span id="cb32-108"><a href="#cb32-108" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-109"><a href="#cb32-109" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-110"><a href="#cb32-110" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-111"><a href="#cb32-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-112"><a href="#cb32-112" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-113"><a href="#cb32-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-114"><a href="#cb32-114" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb32-115"><a href="#cb32-115" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-116"><a href="#cb32-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in the price of the horse as a function of age and sex?"</span>,</span>
<span id="cb32-117"><a href="#cb32-117" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb32-118"><a href="#cb32-118" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (dollars)"</span>) <span class="sc">+</span></span>
<span id="cb32-119"><a href="#cb32-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_parallel_slopes</span>() <span class="sc">+</span></span>
<span id="cb32-120"><a href="#cb32-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-121"><a href="#cb32-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-122"><a href="#cb32-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-123"><a href="#cb32-123" aria-hidden="true" tabindex="-1"></a>There is a difference in price between male and female horses but their prices are not changing across age. This is exactly what we saw in the model summary results. You can also see that the lines are parallel to each other.</span>
<span id="cb32-124"><a href="#cb32-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-125"><a href="#cb32-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## Understanding the summary of a multivariate linear model</span></span>
<span id="cb32-126"><a href="#cb32-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-127"><a href="#cb32-127" aria-hidden="true" tabindex="-1"></a>Given below is the summary output of the multivariate model we built earlier.</span>
<span id="cb32-128"><a href="#cb32-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-129"><a href="#cb32-129" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/lm_summary_multi.png)</span></span>
<span id="cb32-130"><a href="#cb32-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-131"><a href="#cb32-131" aria-hidden="true" tabindex="-1"></a><span class="ss">1.    </span>In section 1, we have the model formula we used for building the model.</span>
<span id="cb32-132"><a href="#cb32-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-133"><a href="#cb32-133" aria-hidden="true" tabindex="-1"></a><span class="ss">2.    </span>In section 2, we have the first quartile, median and third quartile of the residuals of the model. This tells us whether the residuals are normally distributed if the median value is close to zero and, the first and third quartile values are approximately the same in magnitude.</span>
<span id="cb32-134"><a href="#cb32-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-135"><a href="#cb32-135" aria-hidden="true" tabindex="-1"></a><span class="ss">3.    </span>In section 3, we have the coefficient values of the exploratory variables. Please remember that the variable 'sex' has two levels; female and male. By default, R calculates the intercept value for the first level in the first categorical response variable in the model formula. Here, in our case, that first level is female. Therefore, the intercept value gives us the average price value for female horses when age is 0. So here, the y-intercept value of 18199 corresponds to the average price of female horses when age is 0.  The second value is the slope of Age, which is -220.1, which corresponds to a decrease in the price by a value of 220.1 dollars when the age of the horse increases by 1 year. The third value corresponds to the difference in the y-intercept value for males as compared to the main intercept value, which is for females and is 18199. In short, it tells us that male horses with age 0 are priced 17008 dollars more on average when compared to female horses. If we want to see the individual averages of the levels in the categorical exploratory variables, then we should use <span class="in">`-1`</span> in the model formula, which is something we saw in the earlier tutorial.</span>
<span id="cb32-136"><a href="#cb32-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-137"><a href="#cb32-137" aria-hidden="true" tabindex="-1"></a><span class="ss">4.    </span>Section 4 contains metrics which assess model performance. In the earlier tutorial, we saw what residual standard error and R squared values means. Adjusted R square value is a metric similar to R squared value but is calculated for models with multiple explanatory variables. Like R squared, it tells us how much variance seen in the response variable is explained by the explanatory variables and the value lies between 0 and 1. Here we have around 30% variance seen in price explained by both age and sex of the horses.</span>
<span id="cb32-138"><a href="#cb32-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-139"><a href="#cb32-139" aria-hidden="true" tabindex="-1"></a><span class="fu">## Making predictions using a multivariate linear model</span></span>
<span id="cb32-140"><a href="#cb32-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-141"><a href="#cb32-141" aria-hidden="true" tabindex="-1"></a>As seen earlier, we can use the models to predict values outside the dataset. We will use the <span class="in">`expand_grid()`</span> function to make a data frame containing the values for which we want the model to predict.</span>
<span id="cb32-142"><a href="#cb32-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-143"><a href="#cb32-143" aria-hidden="true" tabindex="-1"></a>Let us predict the price of a 20-year-old male horse.</span>
<span id="cb32-144"><a href="#cb32-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-147"><a href="#cb32-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-148"><a href="#cb32-148" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-149"><a href="#cb32-149" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb32-150"><a href="#cb32-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-151"><a href="#cb32-151" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-152"><a href="#cb32-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-153"><a href="#cb32-153" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb32-154"><a href="#cb32-154" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb32-155"><a href="#cb32-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-156"><a href="#cb32-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Making a exploratory data frame</span></span>
<span id="cb32-157"><a href="#cb32-157" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">Sex =</span> <span class="st">"m"</span>,</span>
<span id="cb32-158"><a href="#cb32-158" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Age =</span> <span class="dv">20</span>)</span>
<span id="cb32-159"><a href="#cb32-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-160"><a href="#cb32-160" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting values</span></span>
<span id="cb32-161"><a href="#cb32-161" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_lm, explorartory_values)</span>
<span id="cb32-162"><a href="#cb32-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-163"><a href="#cb32-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-164"><a href="#cb32-164" aria-hidden="true" tabindex="-1"></a>The model predicts that the price of such a horse would be 30806 dollars.</span>
<span id="cb32-165"><a href="#cb32-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-166"><a href="#cb32-166" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assessing a multivariate linear model fit</span></span>
<span id="cb32-167"><a href="#cb32-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-168"><a href="#cb32-168" aria-hidden="true" tabindex="-1"></a><span class="fu">### Adjusted R square value</span></span>
<span id="cb32-169"><a href="#cb32-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-170"><a href="#cb32-170" aria-hidden="true" tabindex="-1"></a>For a simple linear model, we have seen how to interpret the R-squared value, Residual standard error (RSE) value and the Root mean square error (RMSE) value. For a multivariate linear model, the R squared value will be greater compared to a simple linear model and this is because as you add more variables to explain the response variable, the model tends to best fit the available dataset. And in doing so, the model will no longer be useful to make inferences about the general population. So the adjusted R-square value is a metric that describes the percentage of variance explained by the explanatory variable but is measured by penalising the model with multiple explanatory variables by assigning a small penalty term for each additional explanatory variable. The formula for calculating the adjusted R square value is as follows;</span>
<span id="cb32-171"><a href="#cb32-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-172"><a href="#cb32-172" aria-hidden="true" tabindex="-1"></a>$$\bar{R^2} = 1-(1-R^2)\frac{n_{obs}-1}{n_{obs}-n_{var}-1} $$</span>
<span id="cb32-173"><a href="#cb32-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-174"><a href="#cb32-174" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$\bar{R^2}$ = Adjusted R squared value</span>
<span id="cb32-175"><a href="#cb32-175" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$R^2$ = R squared value</span>
<span id="cb32-176"><a href="#cb32-176" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$n_{obs}$ = Number of observations</span>
<span id="cb32-177"><a href="#cb32-177" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$n_{var}$ = Number of variables in the model</span>
<span id="cb32-178"><a href="#cb32-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-179"><a href="#cb32-179" aria-hidden="true" tabindex="-1"></a>Please note that the adjusted R square value is always lower than the R squared value.</span>
<span id="cb32-180"><a href="#cb32-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-181"><a href="#cb32-181" aria-hidden="true" tabindex="-1"></a>In R, we can extract the adjusted R square value of a model using the <span class="in">`glance()`</span> and <span class="in">`pull()`</span> functions in the <span class="in">`{broom}`</span> and <span class="in">`{dplyr}`</span> packages in R. The adjusted R square in the table would be under the <span class="in">`adj.r.squared`</span> column.</span>
<span id="cb32-182"><a href="#cb32-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-185"><a href="#cb32-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-186"><a href="#cb32-186" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-187"><a href="#cb32-187" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-188"><a href="#cb32-188" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb32-189"><a href="#cb32-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-190"><a href="#cb32-190" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-191"><a href="#cb32-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-192"><a href="#cb32-192" aria-hidden="true" tabindex="-1"></a><span class="co"># Building a linear model</span></span>
<span id="cb32-193"><a href="#cb32-193" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Age <span class="sc">+</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb32-194"><a href="#cb32-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-195"><a href="#cb32-195" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting adjusted R square value</span></span>
<span id="cb32-196"><a href="#cb32-196" aria-hidden="true" tabindex="-1"></a>model_lm <span class="sc">%&gt;%</span> <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-197"><a href="#cb32-197" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(adj.r.squared)</span>
<span id="cb32-198"><a href="#cb32-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-199"><a href="#cb32-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-200"><a href="#cb32-200" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linear regression with interacting terms</span></span>
<span id="cb32-201"><a href="#cb32-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-202"><a href="#cb32-202" aria-hidden="true" tabindex="-1"></a>So far we have built linear models using the <span class="in">`HorsePrices`</span> dataset where we looked at the association between age and sex on the price of the horses. Now consider another variable, which is the height of the horses (<span class="in">`Height`</span>). First, let us visualize the heights of the horses of their respective sex.</span>
<span id="cb32-203"><a href="#cb32-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-206"><a href="#cb32-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-207"><a href="#cb32-207" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-208"><a href="#cb32-208" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-209"><a href="#cb32-209" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-210"><a href="#cb32-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-211"><a href="#cb32-211" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-212"><a href="#cb32-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-213"><a href="#cb32-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the data</span></span>
<span id="cb32-214"><a href="#cb32-214" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sex, Height, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb32-215"><a href="#cb32-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Height of horses with respect to their sex"</span>,</span>
<span id="cb32-216"><a href="#cb32-216" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Sex"</span>,</span>
<span id="cb32-217"><a href="#cb32-217" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Height (in hands)"</span>) <span class="sc">+</span></span>
<span id="cb32-218"><a href="#cb32-218" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-219"><a href="#cb32-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-220"><a href="#cb32-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-221"><a href="#cb32-221" aria-hidden="true" tabindex="-1"></a>From the graph, it seems like male horses are typically taller when compared to female horses according to the dataset at hand. Now if we are building a linear model, where we are interested to see the association of height and sex of horses on the price of the horses, we will have to take into consideration that female and male horses have different height distribution, as seen with the box plot above.</span>
<span id="cb32-222"><a href="#cb32-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-223"><a href="#cb32-223" aria-hidden="true" tabindex="-1"></a>One way to account for this is to build separate models using a filtered dataset for each the sex.</span>
<span id="cb32-224"><a href="#cb32-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-227"><a href="#cb32-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-228"><a href="#cb32-228" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-229"><a href="#cb32-229" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-230"><a href="#cb32-230" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-231"><a href="#cb32-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-232"><a href="#cb32-232" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-233"><a href="#cb32-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-234"><a href="#cb32-234" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering horses by their sex</span></span>
<span id="cb32-235"><a href="#cb32-235" aria-hidden="true" tabindex="-1"></a>male_horses <span class="ot">&lt;-</span> HorsePrices <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"m"</span>)</span>
<span id="cb32-236"><a href="#cb32-236" aria-hidden="true" tabindex="-1"></a>female_horses <span class="ot">&lt;-</span> HorsePrices <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"f"</span>)</span>
<span id="cb32-237"><a href="#cb32-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-238"><a href="#cb32-238" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear models</span></span>
<span id="cb32-239"><a href="#cb32-239" aria-hidden="true" tabindex="-1"></a>male_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height, <span class="at">data =</span> male_horses)</span>
<span id="cb32-240"><a href="#cb32-240" aria-hidden="true" tabindex="-1"></a>female_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height, <span class="at">data =</span> female_horses)</span>
<span id="cb32-241"><a href="#cb32-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-242"><a href="#cb32-242" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb32-243"><a href="#cb32-243" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(male_lm)</span>
<span id="cb32-244"><a href="#cb32-244" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(female_lm)</span>
<span id="cb32-245"><a href="#cb32-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-246"><a href="#cb32-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-247"><a href="#cb32-247" aria-hidden="true" tabindex="-1"></a>The coefficient values for the two models are very different. For male horses, a unit change in height contributes to a 9346 dollar increase in the price of the horse, but for female horses, the opposite occurs, a unit change in height decreases the price by 2515 dollars (though this difference is not significantly different). Thus we can say that the height of a horse depends on its sex. In other words, the variable height and the variable sex interact with each other. Instead of making separate models like this, R has an easy way to show interacting terms. Instead of using the <span class="in">`+`</span>, we can use the <span class="in">`*`</span> sign to indicate an interaction between two variables. The <span class="in">`:`</span> sign can also be used to explicitly mention which terms interact. The codes given below show how to account for interaction between height and sex for the given dataset.</span>
<span id="cb32-248"><a href="#cb32-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-251"><a href="#cb32-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-252"><a href="#cb32-252" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-253"><a href="#cb32-253" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-254"><a href="#cb32-254" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-255"><a href="#cb32-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-256"><a href="#cb32-256" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-257"><a href="#cb32-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-258"><a href="#cb32-258" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model with interaction</span></span>
<span id="cb32-259"><a href="#cb32-259" aria-hidden="true" tabindex="-1"></a>lm_model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height <span class="sc">*</span> Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb32-260"><a href="#cb32-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-261"><a href="#cb32-261" aria-hidden="true" tabindex="-1"></a><span class="co"># Same model as above but explicitly mentioning interaction terms</span></span>
<span id="cb32-262"><a href="#cb32-262" aria-hidden="true" tabindex="-1"></a>lm_model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Height <span class="sc">+</span> Sex <span class="sc">+</span> Height<span class="sc">:</span>Sex, <span class="at">data =</span> HorsePrices)</span>
<span id="cb32-263"><a href="#cb32-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-264"><a href="#cb32-264" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb32-265"><a href="#cb32-265" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_1)</span>
<span id="cb32-266"><a href="#cb32-266" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_model_2)</span>
<span id="cb32-267"><a href="#cb32-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-268"><a href="#cb32-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-269"><a href="#cb32-269" aria-hidden="true" tabindex="-1"></a>Since the female is the first level in the variable <span class="in">`Sex`</span>, the intercept is estimated for female horses. This is the same value that we got from the <span class="in">`female_lm`</span> model we made earlier. We also got the slope value for height, which is calculated for female horses (the same value as that from the <span class="in">`female_lm`</span> model). The value for male horses is given as <span class="in">`Sexm`</span> as is -177876, this value is relative to female horses and is given as the difference between the y-intercepts. We can find the actual y-intercept value for males by adding the <span class="in">`Sexm`</span> value and the <span class="in">`(Intercept)`</span> value which is -120546 ( = 57330 + -177876). This is the intercept value for male horses which we got from the <span class="in">`male_lm`</span> model earlier. Now let us look at the <span class="in">`Height:Sexm`</span> value, which is given as 11861. This is the slope value showing how the price change when height change for male horses, but it is calculated relative to female horses. To get the actual slope for male horses, we have to add the slope of <span class="in">`Height`</span> and <span class="in">`Height:Sexm`</span> values. In doing so we get a value of 9346 ( = -2515 + 11861) which is the slope of <span class="in">`Height`</span>, which we got from the <span class="in">`male_lm`</span> model earlier.</span>
<span id="cb32-270"><a href="#cb32-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-271"><a href="#cb32-271" aria-hidden="true" tabindex="-1"></a><span class="fu">## Plotting linear model with an interaction term</span></span>
<span id="cb32-272"><a href="#cb32-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-273"><a href="#cb32-273" aria-hidden="true" tabindex="-1"></a>When we were using the <span class="in">`geom_parallel_slopes()`</span> function from the <span class="in">`{moderndive}`</span> package, I mentioned that we will not use <span class="in">`geom_smooth()`</span> function from the <span class="in">`{ggplot2}`</span> package. This is because when we specify the <span class="in">`col`</span> variable, the <span class="in">`geom_smooth()`</span> function automatically plots the trend line by considering the x-axis variable and the colour variable to be interacting.</span>
<span id="cb32-274"><a href="#cb32-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-277"><a href="#cb32-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-278"><a href="#cb32-278" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Stat2Data)</span>
<span id="cb32-279"><a href="#cb32-279" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-280"><a href="#cb32-280" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-281"><a href="#cb32-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-282"><a href="#cb32-282" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HorsePrices"</span>)</span>
<span id="cb32-283"><a href="#cb32-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-284"><a href="#cb32-284" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting linear model with interaction terms</span></span>
<span id="cb32-285"><a href="#cb32-285" aria-hidden="true" tabindex="-1"></a>HorsePrices <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Height, Price, <span class="at">col =</span> Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-286"><a href="#cb32-286" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Price of horses with respect to their height and sex"</span>,</span>
<span id="cb32-287"><a href="#cb32-287" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Height (in hands)"</span>,</span>
<span id="cb32-288"><a href="#cb32-288" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Price (in dollars)"</span>) <span class="sc">+</span></span>
<span id="cb32-289"><a href="#cb32-289" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-290"><a href="#cb32-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-291"><a href="#cb32-291" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-292"><a href="#cb32-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-293"><a href="#cb32-293" aria-hidden="true" tabindex="-1"></a>The slope for male horses is steeper than for female horses. This indicates that male horses have their price increased significantly as their height increased. Whereas female horses have their price change non significantly when their height change. This is exactly what we see in the <span class="in">`male_lm`</span> and <span class="in">`female_lm`</span> model coefficients.</span>
<span id="cb32-294"><a href="#cb32-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-295"><a href="#cb32-295" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simpson's Paradox</span></span>
<span id="cb32-296"><a href="#cb32-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-297"><a href="#cb32-297" aria-hidden="true" tabindex="-1"></a>Simpson's paradox occurs when a result conveyed using the whole dataset is different from the results conveyed using the different groups within the same dataset. In simple words, the results of the model change drastically due to the inclusion of a variable which was previously not included in the model. Let's see what this means.</span>
<span id="cb32-298"><a href="#cb32-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-299"><a href="#cb32-299" aria-hidden="true" tabindex="-1"></a>We will use the <span class="in">`penguins`</span> dataset from the <span class="in">`{palmerpenguins}`</span> package in R. The dataset contains body measurements taken from three different species of penguins from Antarctica. Let us build a model where the body mass (<span class="in">`body_mass_g`</span>) is predicted by bill depth (<span class="in">`bill_depth_mm`</span>) alone. Let us also build another build with the same model formula as before but this time, we will include an interaction term between bill depth and species (<span class="in">`species`</span>).</span>
<span id="cb32-300"><a href="#cb32-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-303"><a href="#cb32-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-304"><a href="#cb32-304" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(palmerpenguins)) <span class="fu">install.packages</span>(<span class="st">'palmerpenguins'</span>)</span>
<span id="cb32-305"><a href="#cb32-305" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-306"><a href="#cb32-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-307"><a href="#cb32-307" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model</span></span>
<span id="cb32-308"><a href="#cb32-308" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g  <span class="sc">~</span> bill_depth_mm, <span class="at">data =</span> penguins)</span>
<span id="cb32-309"><a href="#cb32-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-310"><a href="#cb32-310" aria-hidden="true" tabindex="-1"></a><span class="co"># Building linear model with interaction term</span></span>
<span id="cb32-311"><a href="#cb32-311" aria-hidden="true" tabindex="-1"></a>model_lm_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g  <span class="sc">~</span> bill_depth_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb32-312"><a href="#cb32-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-313"><a href="#cb32-313" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing model outputs</span></span>
<span id="cb32-314"><a href="#cb32-314" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm)</span>
<span id="cb32-315"><a href="#cb32-315" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_lm_interaction)</span>
<span id="cb32-316"><a href="#cb32-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-317"><a href="#cb32-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-318"><a href="#cb32-318" aria-hidden="true" tabindex="-1"></a>We get a rather interesting and contradicting set of results when we compare the summary outputs for both models. In the model without the species variable, greater bill depth predicts lower body mass in penguins. But, when we add the species variable, the trend reverses, increasing bill depth is associated with an increase in body mass. </span>
<span id="cb32-319"><a href="#cb32-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-320"><a href="#cb32-320" aria-hidden="true" tabindex="-1"></a>It is easier to plot the models and see. Use the slider to see the difference between the plots.</span>
<span id="cb32-321"><a href="#cb32-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-324"><a href="#cb32-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-325"><a href="#cb32-325" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb32-326"><a href="#cb32-326" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-327"><a href="#cb32-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-328"><a href="#cb32-328" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model wihtout interaction term</span></span>
<span id="cb32-329"><a href="#cb32-329" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g)) <span class="sc">+</span></span>
<span id="cb32-330"><a href="#cb32-330" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-331"><a href="#cb32-331" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb32-332"><a href="#cb32-332" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm + species"</span>,</span>
<span id="cb32-333"><a href="#cb32-333" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-334"><a href="#cb32-334" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-335"><a href="#cb32-335" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-336"><a href="#cb32-336" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-337"><a href="#cb32-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-338"><a href="#cb32-338" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model with interaction term</span></span>
<span id="cb32-339"><a href="#cb32-339" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> species)) <span class="sc">+</span></span>
<span id="cb32-340"><a href="#cb32-340" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-341"><a href="#cb32-341" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb32-342"><a href="#cb32-342" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb32-343"><a href="#cb32-343" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-344"><a href="#cb32-344" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-345"><a href="#cb32-345" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-346"><a href="#cb32-346" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-347"><a href="#cb32-347" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-348"><a href="#cb32-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-349"><a href="#cb32-349" aria-hidden="true" tabindex="-1"></a>::: {.juxtapose data-startingposition="50%"}</span>
<span id="cb32-350"><a href="#cb32-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-353"><a href="#cb32-353" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-354"><a href="#cb32-354" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-355"><a href="#cb32-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-356"><a href="#cb32-356" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model wihtout interaction term</span></span>
<span id="cb32-357"><a href="#cb32-357" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g)) <span class="sc">+</span></span>
<span id="cb32-358"><a href="#cb32-358" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-359"><a href="#cb32-359" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb32-360"><a href="#cb32-360" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm + species"</span>,</span>
<span id="cb32-361"><a href="#cb32-361" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-362"><a href="#cb32-362" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-363"><a href="#cb32-363" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-364"><a href="#cb32-364" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-365"><a href="#cb32-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-366"><a href="#cb32-366" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the model with interaction term</span></span>
<span id="cb32-367"><a href="#cb32-367" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> species)) <span class="sc">+</span></span>
<span id="cb32-368"><a href="#cb32-368" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-369"><a href="#cb32-369" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth in three different species of penguins"</span>,</span>
<span id="cb32-370"><a href="#cb32-370" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb32-371"><a href="#cb32-371" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-372"><a href="#cb32-372" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-373"><a href="#cb32-373" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb32-374"><a href="#cb32-374" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-375"><a href="#cb32-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-376"><a href="#cb32-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-377"><a href="#cb32-377" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb32-378"><a href="#cb32-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-379"><a href="#cb32-379" aria-hidden="true" tabindex="-1"></a>So it is always better to visualize the dataset and build models according to the question at hand.</span>
<span id="cb32-380"><a href="#cb32-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-381"><a href="#cb32-381" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualizing linear models with two numerical explanatory variables</span></span>
<span id="cb32-382"><a href="#cb32-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-383"><a href="#cb32-383" aria-hidden="true" tabindex="-1"></a>Often you will be building models with two or more two explanatory variables. If some of those explanatory variables are categorical then it is easier to plot them as we can assign different colour or shape variables and we can also use faceting. But if they are all numerical variables then it is kind of difficult to plot them. We can either rely on three-dimensional plots or use a continuous colour scale gradient in a two-dimensional plot. Let us see how to plot the graphs.</span>
<span id="cb32-384"><a href="#cb32-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-385"><a href="#cb32-385" aria-hidden="true" tabindex="-1"></a>We will again use the <span class="in">`penguins`</span> dataset from the <span class="in">`{palmerpenguins}`</span> package in R. We will build a model to predict body mass (<span class="in">`body_mass_g`</span>) using bill length (<span class="in">`bill_length_mm`</span>) and bill depth (<span class="in">`bill_depth_mm`</span>). Let us first try to plot a 3D plot using the <span class="in">`scatter3D()`</span> function from the <span class="in">`{plot3D}`</span> package in R. </span>
<span id="cb32-386"><a href="#cb32-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-389"><a href="#cb32-389" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-390"><a href="#cb32-390" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(plot3D)) <span class="fu">install.packages</span>(<span class="st">'plot3D'</span>)</span>
<span id="cb32-391"><a href="#cb32-391" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plot3D)</span>
<span id="cb32-392"><a href="#cb32-392" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-393"><a href="#cb32-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-394"><a href="#cb32-394" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting a 3D plot</span></span>
<span id="cb32-395"><a href="#cb32-395" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter3D</span>(penguins<span class="sc">$</span>body_mass_g, penguins<span class="sc">$</span>bill_depth_mm, penguins<span class="sc">$</span>bill_length_mm)</span>
<span id="cb32-396"><a href="#cb32-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-397"><a href="#cb32-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-398"><a href="#cb32-398" aria-hidden="true" tabindex="-1"></a>Well, 3D plotting is a mess, as you can see from the above plot. It is very hard to make out any useful findings using the graph above. So instead of this, we can return to our conventional 2D plot where we can use a continuous colour gradient to visualize the third numerical variable.</span>
<span id="cb32-399"><a href="#cb32-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-402"><a href="#cb32-402" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-403"><a href="#cb32-403" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-404"><a href="#cb32-404" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-405"><a href="#cb32-405" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-406"><a href="#cb32-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-407"><a href="#cb32-407" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb32-408"><a href="#cb32-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-409"><a href="#cb32-409" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph</span></span>
<span id="cb32-410"><a href="#cb32-410" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb32-411"><a href="#cb32-411" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-412"><a href="#cb32-412" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth and bill length in three different species of penguins"</span>,</span>
<span id="cb32-413"><a href="#cb32-413" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"body_mass_g  ~ bill_depth_mm * species"</span>,</span>
<span id="cb32-414"><a href="#cb32-414" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-415"><a href="#cb32-415" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-416"><a href="#cb32-416" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb32-417"><a href="#cb32-417" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-418"><a href="#cb32-418" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-419"><a href="#cb32-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-420"><a href="#cb32-420" aria-hidden="true" tabindex="-1"></a>From the graph, it roughly seems like penguins with greater body mass have a longer and narrower bill. We can further subdivide this plot by the species category using faceting.</span>
<span id="cb32-421"><a href="#cb32-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-424"><a href="#cb32-424" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-425"><a href="#cb32-425" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-426"><a href="#cb32-426" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-427"><a href="#cb32-427" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-428"><a href="#cb32-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-429"><a href="#cb32-429" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb32-430"><a href="#cb32-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-431"><a href="#cb32-431" aria-hidden="true" tabindex="-1"></a><span class="co"># Making a function to make line breaks in text</span></span>
<span id="cb32-432"><a href="#cb32-432" aria-hidden="true" tabindex="-1"></a>addline_format <span class="ot">&lt;-</span> <span class="cf">function</span>(x,...){</span>
<span id="cb32-433"><a href="#cb32-433" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gsub</span>(<span class="st">','</span>,<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>,x)}</span>
<span id="cb32-434"><a href="#cb32-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-435"><a href="#cb32-435" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph</span></span>
<span id="cb32-436"><a href="#cb32-436" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb32-437"><a href="#cb32-437" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-438"><a href="#cb32-438" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">addline_format</span>(<span class="st">"Body mass predcited by bill depth and bill length,in three different species of penguins"</span>),</span>
<span id="cb32-439"><a href="#cb32-439" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-440"><a href="#cb32-440" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-441"><a href="#cb32-441" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb32-442"><a href="#cb32-442" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> species) <span class="sc">+</span></span>
<span id="cb32-443"><a href="#cb32-443" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-444"><a href="#cb32-444" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-445"><a href="#cb32-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-446"><a href="#cb32-446" aria-hidden="true" tabindex="-1"></a>When we group the data according to different species, we get the opposite result as compared before. Here, we can see that penguins with heavier body mass have broader and longer bills.</span>
<span id="cb32-447"><a href="#cb32-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-448"><a href="#cb32-448" aria-hidden="true" tabindex="-1"></a>Now let us plot the predicted values from the linear models to see the general trend of the data.</span>
<span id="cb32-449"><a href="#cb32-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-452"><a href="#cb32-452" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-453"><a href="#cb32-453" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb32-454"><a href="#cb32-454" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-455"><a href="#cb32-455" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-456"><a href="#cb32-456" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb32-457"><a href="#cb32-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-458"><a href="#cb32-458" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"penguins"</span>)</span>
<span id="cb32-459"><a href="#cb32-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-460"><a href="#cb32-460" aria-hidden="true" tabindex="-1"></a><span class="co"># Making prediction</span></span>
<span id="cb32-461"><a href="#cb32-461" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> bill_depth_mm <span class="sc">*</span> bill_length_mm, <span class="at">data =</span> penguins)</span>
<span id="cb32-462"><a href="#cb32-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-463"><a href="#cb32-463" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb32-464"><a href="#cb32-464" aria-hidden="true" tabindex="-1"></a>  <span class="at">bill_depth_mm =</span> <span class="fu">seq</span>(<span class="dv">15</span>,<span class="dv">25</span>,<span class="dv">1</span>),</span>
<span id="cb32-465"><a href="#cb32-465" aria-hidden="true" tabindex="-1"></a>  <span class="at">bill_length_mm =</span> <span class="fu">seq</span>(<span class="dv">30</span>,<span class="dv">60</span>,<span class="dv">1</span>),</span>
<span id="cb32-466"><a href="#cb32-466" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-467"><a href="#cb32-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-468"><a href="#cb32-468" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="ot">&lt;-</span> explorartory_values <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb32-469"><a href="#cb32-469" aria-hidden="true" tabindex="-1"></a>  <span class="at">body_mass_g =</span> <span class="fu">predict</span>(model_lm, explorartory_values)</span>
<span id="cb32-470"><a href="#cb32-470" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-471"><a href="#cb32-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-472"><a href="#cb32-472" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph with predicted values</span></span>
<span id="cb32-473"><a href="#cb32-473" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(bill_depth_mm, body_mass_g, <span class="at">col =</span> bill_length_mm)) <span class="sc">+</span></span>
<span id="cb32-474"><a href="#cb32-474" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-475"><a href="#cb32-475" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Body mass predcited by bill depth and bill length </span></span>
<span id="cb32-476"><a href="#cb32-476" aria-hidden="true" tabindex="-1"></a><span class="st">in three different species of penguins"</span>,</span>
<span id="cb32-477"><a href="#cb32-477" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Bill depth (mm)"</span>,</span>
<span id="cb32-478"><a href="#cb32-478" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body mass (g)"</span>) <span class="sc">+</span></span>
<span id="cb32-479"><a href="#cb32-479" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"inferno"</span>) <span class="sc">+</span></span>
<span id="cb32-480"><a href="#cb32-480" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> species) <span class="sc">+</span></span>
<span id="cb32-481"><a href="#cb32-481" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> predicted_values, <span class="fu">aes</span>(<span class="at">y =</span> body_mass_g), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb32-482"><a href="#cb32-482" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-483"><a href="#cb32-483" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-484"><a href="#cb32-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-485"><a href="#cb32-485" aria-hidden="true" tabindex="-1"></a>We got a nice gradient-coloured graph. From the predicted values we got from the model we can understand how body mass changes with bill depth and bill length. We can see two clear patterns. For penguins with lower bill length values, the body mass increases as bill depth increases. The opposite is true for penguins with larger values for bill length. For these penguins, body mass decreases as bill depth increases.</span>
<span id="cb32-486"><a href="#cb32-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-487"><a href="#cb32-487" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualizing logistic models with two numerical explanatory variables</span></span>
<span id="cb32-488"><a href="#cb32-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-489"><a href="#cb32-489" aria-hidden="true" tabindex="-1"></a>We have seen how to include two or more variables in a linear model. The same procedure applies to logistic models. Now we will see how to visualize a logistic model with two or more numerical variables.</span>
<span id="cb32-490"><a href="#cb32-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-491"><a href="#cb32-491" aria-hidden="true" tabindex="-1"></a>We will use the <span class="in">`CreditCard`</span> dataset in the <span class="in">`{AER}`</span> package in R. The dataset contains the credit history of a sample of applicants for a type of credit card. We will predict to see the success of the acceptance of the credit card application (<span class="in">`card`</span>) using the yearly income (<span class="in">`income`</span>) and age (<span class="in">`age`</span>) of the applicant. The code for making the plot is very similar to that we have seen earlier.</span>
<span id="cb32-492"><a href="#cb32-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-495"><a href="#cb32-495" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-496"><a href="#cb32-496" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(AER)) <span class="fu">install.packages</span>(<span class="st">'AER'</span>)</span>
<span id="cb32-497"><a href="#cb32-497" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb32-498"><a href="#cb32-498" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-499"><a href="#cb32-499" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-500"><a href="#cb32-500" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb32-501"><a href="#cb32-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-502"><a href="#cb32-502" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"CreditCard"</span>)</span>
<span id="cb32-503"><a href="#cb32-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-504"><a href="#cb32-504" aria-hidden="true" tabindex="-1"></a><span class="co"># Making prediction</span></span>
<span id="cb32-505"><a href="#cb32-505" aria-hidden="true" tabindex="-1"></a>model_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(card <span class="sc">~</span> income <span class="sc">*</span> age, <span class="at">data =</span> CreditCard, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb32-506"><a href="#cb32-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-507"><a href="#cb32-507" aria-hidden="true" tabindex="-1"></a>explorartory_values <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb32-508"><a href="#cb32-508" aria-hidden="true" tabindex="-1"></a>  <span class="at">income =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">20</span>,<span class="dv">1</span>),</span>
<span id="cb32-509"><a href="#cb32-509" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">90</span>,<span class="dv">1</span>),</span>
<span id="cb32-510"><a href="#cb32-510" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-511"><a href="#cb32-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-512"><a href="#cb32-512" aria-hidden="true" tabindex="-1"></a>predicted_values <span class="ot">&lt;-</span> explorartory_values <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb32-513"><a href="#cb32-513" aria-hidden="true" tabindex="-1"></a>  <span class="at">card =</span> <span class="fu">predict</span>(model_logistic, explorartory_values, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb32-514"><a href="#cb32-514" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-515"><a href="#cb32-515" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-516"><a href="#cb32-516" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the graph with predicted values</span></span>
<span id="cb32-517"><a href="#cb32-517" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(CreditCard, <span class="fu">aes</span>(income, <span class="fu">as.integer</span>(card)<span class="sc">-</span><span class="dv">1</span>, <span class="at">col =</span> age)) <span class="sc">+</span></span>
<span id="cb32-518"><a href="#cb32-518" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb32-519"><a href="#cb32-519" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Does income and age affect the success in accepting a credit card application?"</span>,</span>
<span id="cb32-520"><a href="#cb32-520" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Yearly income (in USD 10,000)"</span>,</span>
<span id="cb32-521"><a href="#cb32-521" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability of success in accepting a credit card application"</span>) <span class="sc">+</span></span>
<span id="cb32-522"><a href="#cb32-522" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient2</span>() <span class="sc">+</span></span>
<span id="cb32-523"><a href="#cb32-523" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> predicted_values, <span class="fu">aes</span>(<span class="at">y =</span> card), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb32-524"><a href="#cb32-524" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb32-525"><a href="#cb32-525" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-526"><a href="#cb32-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-527"><a href="#cb32-527" aria-hidden="true" tabindex="-1"></a>We get some interesting results. People with higher yearly incomes have a higher chance of getting a credit card. But for age, younger people with lower yearly income have more chance of getting a credit card as compared to older people with the same level of yearly income. But this trend reverses when yearly income crosses 50,000 dollars.</span>
<span id="cb32-528"><a href="#cb32-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-529"><a href="#cb32-529" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb32-530"><a href="#cb32-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-531"><a href="#cb32-531" aria-hidden="true" tabindex="-1"></a>It is time to wrap up! In this tutorial we have learned the following things;</span>
<span id="cb32-532"><a href="#cb32-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-533"><a href="#cb32-533" aria-hidden="true" tabindex="-1"></a><span class="ss">1.    </span>How to build models with two or more explanatory variables</span>
<span id="cb32-534"><a href="#cb32-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-535"><a href="#cb32-535" aria-hidden="true" tabindex="-1"></a><span class="ss">2.    </span>How to interpret multivariate models</span>
<span id="cb32-536"><a href="#cb32-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-537"><a href="#cb32-537" aria-hidden="true" tabindex="-1"></a><span class="ss">3.    </span>How to predict values using a multivariate model</span>
<span id="cb32-538"><a href="#cb32-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-539"><a href="#cb32-539" aria-hidden="true" tabindex="-1"></a><span class="ss">4.    </span>Assessing a multivariate model</span>
<span id="cb32-540"><a href="#cb32-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-541"><a href="#cb32-541" aria-hidden="true" tabindex="-1"></a><span class="ss">5.    </span>Building models with interaction terms and plotting them</span>
<span id="cb32-542"><a href="#cb32-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-543"><a href="#cb32-543" aria-hidden="true" tabindex="-1"></a><span class="ss">6.    </span>What is Simpson's paradox</span>
<span id="cb32-544"><a href="#cb32-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-545"><a href="#cb32-545" aria-hidden="true" tabindex="-1"></a><span class="ss">7.    </span>Visualising models with two numerical explanatory variables</span>
<span id="cb32-546"><a href="#cb32-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-547"><a href="#cb32-547" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- Do not forget to put flag counter --&gt;</span></span>
<span id="cb32-548"><a href="#cb32-548" aria-hidden="true" tabindex="-1"></a><span class="kw">&lt;a</span> <span class="er">hidden</span> <span class="er">href</span><span class="ot">=</span><span class="st">"https://info.flagcounter.com/ynrK"</span><span class="kw">&gt;&lt;img</span> <span class="er">src</span><span class="ot">=</span><span class="st">"https://s11.flagcounter.com/count2/ynrK/bg_000000/txt_FFFFFF/border_F0F0F0/columns_5/maxflags_25/viewers_0/labels_1/pageviews_1/flags_0/percent_0/"</span> <span class="er">alt</span><span class="ot">=</span><span class="st">"Flag Counter"</span> <span class="er">border</span><span class="ot">=</span><span class="st">"0"</span><span class="kw">/&gt;&lt;/a&gt;</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Blog made using <a href="https://quarto.org/">Quarto®</a> with ❤️, by Jewel Johnson.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jeweljohnsonj">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/jeweljohnsonj">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:jewel.johnson@bsu.edu">
      <i class="bi bi-briefcase" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:jeweljohnsonj@gmail.com">
      <i class="bi bi-house" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>
<div class="page-columns page-rows-contents page-layout-article"><div class="social-share"><a href="https://twitter.com/share?url=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html&amp;text=Intermediate Regression in R" target="_blank" class="twitter"><i class="fab fa-twitter fa-fw fa-lg"></i></a><a href="https://www.linkedin.com/shareArticle?url=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html&amp;title=Intermediate Regression in R" target="_blank" class="linkedin"><i class="fa-brands fa-linkedin-in fa-fw fa-lg"></i></a>  <a href="mailto:?subject=Intermediate Regression in R&amp;body=Check out this link:https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html" target="_blank" class="email"><i class="fa-solid fa-envelope fa-fw fa-lg"></i></a><a href="https://www.facebook.com/sharer.php?u=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html" target="_blank" class="facebook"><i class="fab fa-facebook-f fa-fw fa-lg"></i></a><a href="https://reddit.com/submit?url=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html&amp;title=Intermediate Regression in R" target="_blank" class="reddit">   <i class="fa-brands fa-reddit-alien fa-fw fa-lg"></i></a><a href="https://www.stumbleupon.com/submit?url=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html&amp;title=Intermediate Regression in R" target="_blank" class="stumbleupon"><i class="fa-brands fa-stumbleupon fa-fw fa-lg"></i></a><a href="https://www.tumblr.com/share/link?url=https://sciquest.netlify.app/tutorials/stat_model/inter_reg.html&amp;name=Intermediate Regression in R" target="_blank" class="tumblr"><i class="fa-brands fa-tumblr fa-fw fa-lg"></i></a></div></div>



<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>